# Generated by Django 4.1.1 on 2022-09-05 21:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("court_types", "0001_initial"),
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Court",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("capacity", models.IntegerField()),
                ("is_indoor", models.BooleanField(default=False)),
                (
                    "court_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courts",
                        to="court_types.court_type",
                    ),
                ),
                (
                    "sport_facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courts",
                        to="facilities.facility",
                    ),
                ),
            ],
        ),
    ]
