# Generated by Django 4.1.1 on 2022-09-13 16:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Court",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=127)),
                ("capacity", models.IntegerField()),
                ("is_indoor", models.BooleanField(default=False)),
                ("price_by_hour", models.DecimalField(decimal_places=2, max_digits=10)),
                ("max_schedule_range_in_days", models.IntegerField()),
                ("sport", models.CharField(max_length=127)),
                ("opening_hour", models.TimeField()),
                ("closing_hour", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="NonOperatingDay",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "regular_day_off",
                    models.CharField(
                        choices=[
                            ("MONDAY", "Monday"),
                            ("TUESDAY", "Tuesday"),
                            ("WEDNESDAY", "Wednesday"),
                            ("THURSDAY", "Thursday"),
                            ("FRIDAY", "Friday"),
                            ("SATURDAY", "Saturday"),
                            ("SUNDAY", "Sunday"),
                            ("DEFAULT", "Default"),
                        ],
                        default="DEFAULT",
                        max_length=9,
                    ),
                ),
                (
                    "court",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="non_operating_days",
                        to="courts.court",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("holiday", models.DateField()),
                (
                    "court",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="courts.court",
                    ),
                ),
            ],
        ),
    ]
