# Generated by Django 4.1.1 on 2022-09-13 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courts", "0001_initial"),
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="court",
            name="sport_facility",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courts",
                to="facilities.facility",
            ),
        ),
    ]
