# Generated by Django 4.1.1 on 2022-09-08 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("court_types", "0001_initial"),
        ("facilities", "0003_alter_facility_address"),
        ("courts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="court",
            name="court_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courts",
                to="court_types.court_type",
            ),
        ),
        migrations.AlterField(
            model_name="court",
            name="sport_facility",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courts",
                to="facilities.facility",
            ),
        ),
    ]
