# Generated by Django 4.1.1 on 2022-09-09 16:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0004_rename_closing_hour_court_holidays_closing_hour_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nonoperatingdays",
            name="holidays",
        ),
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("holidays", models.DateField(blank=True, null=True)),
                (
                    "court",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="courts.court",
                    ),
                ),
            ],
        ),
    ]
