# Generated by Django 4.1.1 on 2022-09-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0005_remove_nonoperatingdays_holidays_holiday"),
    ]

    operations = [
        migrations.RenameField(
            model_name="court",
            old_name="holidays_closing_hour",
            new_name="closing_hour",
        ),
        migrations.RenameField(
            model_name="court",
            old_name="holidays_opening_hour",
            new_name="opening_hour",
        ),
        migrations.RemoveField(
            model_name="court",
            name="weekdays_closing_hour",
        ),
        migrations.RemoveField(
            model_name="court",
            name="weekdays_opening_hour",
        ),
        migrations.RemoveField(
            model_name="court",
            name="weekends_closing_hour",
        ),
        migrations.RemoveField(
            model_name="court",
            name="weekends_opening_hour",
        ),
        migrations.AddField(
            model_name="court",
            name="price_by_hour",
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
    ]
