# Generated by Django 4.1.1 on 2022-09-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0006_rename_holidays_closing_hour_court_closing_hour_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="court",
            name="max_schedule_range_in_months",
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
