# Generated by Django 4.1.1 on 2022-09-11 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courts", "0002_alter_court_court_type"),
        ("courts", "0007_court_max_schedule_range_in_months"),
    ]

    operations = []
