# Generated by Django 4.1.1 on 2022-09-11 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("court_types", "0001_initial"),
        ("courts", "0008_merge_20220911_1403"),
    ]

    operations = [
        migrations.AlterField(
            model_name="court",
            name="court_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courts",
                to="court_types.court_type",
            ),
        ),
    ]
