# Generated by Django 4.1.1 on 2022-09-05 21:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Court_type",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sport", models.CharField(max_length=60)),
                ("type", models.CharField(max_length=60)),
            ],
        ),
    ]
