# Generated by Django 4.1.1 on 2022-09-12 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facility",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="facilities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
