# Generated by Django 4.1.1 on 2022-09-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
