# Generated by Django 4.1.1 on 2022-09-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facilities", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="email",
            field=models.EmailField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name="facility",
            name="name",
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name="facility",
            name="phone_number",
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
