# Generated by Django 4.1.1 on 2022-09-08 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0001_initial"),
        ("facilities", "0002_alter_facility_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='addresses.address'),
        ),
    ]
