# Generated by Django 4.1.1 on 2022-09-05 21:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment_information",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("number", models.IntegerField()),
                ("code", models.IntegerField()),
                ("expiration_date", models.DateField()),
            ],
        ),
    ]
