# Generated by Django 4.1.1 on 2022-09-13 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payment_informations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentinformation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payment_informations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
