# Generated by Django 4.1.1 on 2022-09-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="datetime",
            field=models.DateTimeField(),
        ),
    ]
