# Generated by Django 4.1.1 on 2022-09-09 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0004_alter_schedule_datetime"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="is_available",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="price",
        ),
    ]
