# Generated by Django 4.1.1 on 2022-09-13 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0005_alter_schedule_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="schedule",
            name="unique_datetime_by_court",
        ),
    ]
